title: Revathi - Portfolio
description: "AWS Certified | Site Reliability Engineer (SRE) | Cloud & Application Support"
theme: jekyll-theme-cayman
author: Revathi Dhayalan
email: reytech89@gmail.com
github_username: reytech89
linkedin_username: revathi-dhayalan
