yaml
title: Revathi - Portfolio
description: AWS Certified | Site Reliability Engineer (SRE) | Cloud & Application Support
theme: jekyll-theme-cayman

# Add your information
author: Revathi Dhayalan
email: reytech89@gmail.com
github_username: https://github.com/reytech89
linkedin_username: https://www.linkedin.com/in/revathi-dhayalan/
